@url=http://localhost:3000 
### 
GET {{url}}/users

### 

POST {{url}}/users 
content-type: application/json

{
"name": "TESTPOST4.name",
"email": "TESTPOST4.mail",
"phonenumber":"TESTPOST4.phone",
"password":"TESTPOST4.pw"
}

###
GET {{url}}/users/1

###
PUT {{url}}/users/1
Content-Type: application/json

{
"name":"User1New"
}

###
PUT {{url}}/users/2
Content-Type: application/json

{
"name": "TESTPUT2.name",
"email": "TESTPUT2.email",
"phonenumber":"TESTPUT2.phone",
"password":"TESTPUT2.pw"
}

###
PUT {{url}}/users/3
Content-Type: application/json

{
"name": "TESTPUT3.namepartial",
"email": "TESTPUT3.emailpartial"
}

###
DELETE {{url}}/users/4

###
GET {{url}}/recipes?sortby=title&sort=asc&limit=10

### 

GET {{url}}/recipes/

### 

POST {{url}}/recipes
content-type: application/json

{
"title":"Test Recipe2",
"ingredients":"Test Ingredients2",
"photo":"Testdomain.com/photo2",
"users_id":"3"
}

###
PUT {{url}}/recipes/1
content-type: application/json

{
"title":"Sandwich with Telur"
}

###
GET {{url}}/recipes/
###

POST {{url}}/categories
content-type: application/json

{
"category_name":"Breakfast"
}

###
DELETE {{url}}/recipes/4